name: Maven Package Publish to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

env:
  JAVA_VERSION: 8

permissions:
  contents: read
  packages: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }}
          
      - name: Build with Maven
        run: mvn -B -DskipTests clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
      - name: Publish to GitHub Packages Apache Maven
        if: github.event_name == 'release'
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
